### ISSUE TITLE
PropTypes Error with React 16

### ISSUE THREAD

**Issue by Isarstyle** [zackargyle/react-analog-clock#4]
react-analog-clock should make use of prop-types package instead of React.PropTypes
Can you please update your package? Would love to continue using your clock package. 

Thank you

**Comment by zackargyle** [comment]
Would you like to try your hand at contributing a pull request with update? That would be super helpful and I'd be happy to review!

**Comment by Isarstyle** [comment]
#5 here you go.

**Comment by zackargyle** [comment]
Thanks for helping! I bumped to `2.0.0` since it's a breaking change. It's published and ready to use!
